name: Daily Option Chain Download to SQLite

on:
  schedule:
    - cron: '59 21 * * *'  # ogni giorno alle 23:59 UTC
  workflow_dispatch:

jobs:
  download_option_chain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run download script
      run: python download_option_chain.py

    - name: Upload SQLite DB artifact
      uses: actions/upload-artifact@v4
      with:
        name: option_chain_db
        path: data/option_chains.db
