name: Daily Option Chain Download to SQLite
permissions:
  contents: write

on:
  schedule:
    - cron: '59 21 * * *'  # ogni giorno alle 23:59 UTC
  workflow_dispatch:

jobs:
  download_option_chain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Show DB status BEFORE script
      run: |
        ls -l data/option_chains.db || echo "DB does not exist yet"
        python -c "import sqlite3; import os; db='data/option_chains.db'; print('DB exists:', os.path.exists(db)); print('Rows:', sqlite3.connect(db).execute('SELECT COUNT(*) FROM option_chain').fetchone()[0])" || echo "No rows yet or table missing"

    - name: Run download script
      run: python retriever.py

    - name: Show DB status AFTER script
      run: |
        ls -l data/option_chains.db
        python -c "import sqlite3; db='data/option_chains.db'; print('Rows:', sqlite3.connect(db).execute('SELECT COUNT(*) FROM option_chain').fetchone()[0])"

    - name: Configure Git for GitHub Actions
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit & push updated DB
      run: |
        git add data/option_chains.db
        git commit -m "Update DB - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
